/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectosemestral.Vistas.administrador.Vendedor;

import Modelo.Cliente;
import Modelo.Empleado;
import javax.swing.JOptionPane;

/**
 *
 * @author cetecom
 */
public class Nuevo_Vendedor extends javax.swing.JFrame {

    /**
     * Creates new form Nuevo_vendedor1
     */
    public Nuevo_Vendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pane_fondo_Nuevo_Cliente1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pane_fondo_identifi = new javax.swing.JPanel();
        lbl_identificacion = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        pane_fondo_Nombre = new javax.swing.JPanel();
        lbl_Nombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        pane_fondo_Nombre1 = new javax.swing.JPanel();
        lbl_Nombre1 = new javax.swing.JLabel();
        txtApellidop = new javax.swing.JTextField();
        pane_fondo_Nombre3 = new javax.swing.JPanel();
        lbl_Nombre3 = new javax.swing.JLabel();
        txtApellidom = new javax.swing.JTextField();
        pane_fondo_direccion = new javax.swing.JPanel();
        lbl_Direccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        pane_fondo_email = new javax.swing.JPanel();
        lbl_e_email = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        pane_fondo_N = new javax.swing.JPanel();
        lbl_telefono = new javax.swing.JLabel();
        txtNrTelefono = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        pane_fondo_N1 = new javax.swing.JPanel();
        lbl_Contrasenia = new javax.swing.JLabel();
        txtcontrasenia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo Vendedor");

        jPanel1.setBackground(new java.awt.Color(207, 207, 207));

        pane_fondo_Nuevo_Cliente1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nuevo Vendedor");

        javax.swing.GroupLayout pane_fondo_Nuevo_Cliente1Layout = new javax.swing.GroupLayout(pane_fondo_Nuevo_Cliente1);
        pane_fondo_Nuevo_Cliente1.setLayout(pane_fondo_Nuevo_Cliente1Layout);
        pane_fondo_Nuevo_Cliente1Layout.setHorizontalGroup(
            pane_fondo_Nuevo_Cliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_Nuevo_Cliente1Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pane_fondo_Nuevo_Cliente1Layout.setVerticalGroup(
            pane_fondo_Nuevo_Cliente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_Nuevo_Cliente1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pane_fondo_identifi.setBackground(new java.awt.Color(153, 153, 153));

        lbl_identificacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_identificacion.setForeground(new java.awt.Color(255, 255, 255));
        lbl_identificacion.setText("Idenificacion");

        javax.swing.GroupLayout pane_fondo_identifiLayout = new javax.swing.GroupLayout(pane_fondo_identifi);
        pane_fondo_identifi.setLayout(pane_fondo_identifiLayout);
        pane_fondo_identifiLayout.setHorizontalGroup(
            pane_fondo_identifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_identifiLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(lbl_identificacion)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        pane_fondo_identifiLayout.setVerticalGroup(
            pane_fondo_identifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_identifiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_identificacion)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        txtIdentificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdentificacion.setText(" Pasaporte / RUT");
        txtIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacionActionPerformed(evt);
            }
        });

        pane_fondo_Nombre.setBackground(new java.awt.Color(176, 176, 176));

        lbl_Nombre.setBackground(new java.awt.Color(238, 238, 238));
        lbl_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre.setText("Nombre");

        javax.swing.GroupLayout pane_fondo_NombreLayout = new javax.swing.GroupLayout(pane_fondo_Nombre);
        pane_fondo_Nombre.setLayout(pane_fondo_NombreLayout);
        pane_fondo_NombreLayout.setHorizontalGroup(
            pane_fondo_NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_NombreLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(lbl_Nombre)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        pane_fondo_NombreLayout.setVerticalGroup(
            pane_fondo_NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_NombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Nombre)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setText("Nombre");

        pane_fondo_Nombre1.setBackground(new java.awt.Color(176, 176, 176));

        lbl_Nombre1.setBackground(new java.awt.Color(238, 238, 238));
        lbl_Nombre1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre1.setText("Apellido Paterno");

        javax.swing.GroupLayout pane_fondo_Nombre1Layout = new javax.swing.GroupLayout(pane_fondo_Nombre1);
        pane_fondo_Nombre1.setLayout(pane_fondo_Nombre1Layout);
        pane_fondo_Nombre1Layout.setHorizontalGroup(
            pane_fondo_Nombre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_Nombre1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(lbl_Nombre1)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        pane_fondo_Nombre1Layout.setVerticalGroup(
            pane_fondo_Nombre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_Nombre1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Nombre1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtApellidop.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellidop.setText("Apellido");

        pane_fondo_Nombre3.setBackground(new java.awt.Color(176, 176, 176));

        lbl_Nombre3.setBackground(new java.awt.Color(238, 238, 238));
        lbl_Nombre3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nombre3.setText("Apellido Materno");

        javax.swing.GroupLayout pane_fondo_Nombre3Layout = new javax.swing.GroupLayout(pane_fondo_Nombre3);
        pane_fondo_Nombre3.setLayout(pane_fondo_Nombre3Layout);
        pane_fondo_Nombre3Layout.setHorizontalGroup(
            pane_fondo_Nombre3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_Nombre3Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(lbl_Nombre3)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        pane_fondo_Nombre3Layout.setVerticalGroup(
            pane_fondo_Nombre3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_Nombre3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Nombre3)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        txtApellidom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellidom.setText("Apellido");
        txtApellidom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidomActionPerformed(evt);
            }
        });

        pane_fondo_direccion.setBackground(new java.awt.Color(176, 176, 176));

        lbl_Direccion.setBackground(new java.awt.Color(238, 238, 238));
        lbl_Direccion.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Direccion.setText("DIRECCION");

        javax.swing.GroupLayout pane_fondo_direccionLayout = new javax.swing.GroupLayout(pane_fondo_direccion);
        pane_fondo_direccion.setLayout(pane_fondo_direccionLayout);
        pane_fondo_direccionLayout.setHorizontalGroup(
            pane_fondo_direccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_direccionLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(lbl_Direccion)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        pane_fondo_direccionLayout.setVerticalGroup(
            pane_fondo_direccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_direccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Direccion)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        txtDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDireccion.setText(" Direccion");

        pane_fondo_email.setBackground(new java.awt.Color(176, 176, 176));

        lbl_e_email.setBackground(new java.awt.Color(238, 238, 238));
        lbl_e_email.setForeground(new java.awt.Color(255, 255, 255));
        lbl_e_email.setText("E-EMAIL");

        javax.swing.GroupLayout pane_fondo_emailLayout = new javax.swing.GroupLayout(pane_fondo_email);
        pane_fondo_email.setLayout(pane_fondo_emailLayout);
        pane_fondo_emailLayout.setHorizontalGroup(
            pane_fondo_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_emailLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(lbl_e_email)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        pane_fondo_emailLayout.setVerticalGroup(
            pane_fondo_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_emailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_e_email)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setText("EXAMPLE@DUOCUC.CL");

        pane_fondo_N.setBackground(new java.awt.Color(176, 176, 176));

        lbl_telefono.setBackground(new java.awt.Color(238, 238, 238));
        lbl_telefono.setForeground(new java.awt.Color(255, 255, 255));
        lbl_telefono.setText("N°TELEFONO");

        javax.swing.GroupLayout pane_fondo_NLayout = new javax.swing.GroupLayout(pane_fondo_N);
        pane_fondo_N.setLayout(pane_fondo_NLayout);
        pane_fondo_NLayout.setHorizontalGroup(
            pane_fondo_NLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_NLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(lbl_telefono)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        pane_fondo_NLayout.setVerticalGroup(
            pane_fondo_NLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_NLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_telefono)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        txtNrTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNrTelefono.setText("+56  9 5555 5555");

        btn_aceptar.setBackground(new java.awt.Color(102, 102, 102));
        btn_aceptar.setForeground(new java.awt.Color(255, 255, 255));
        btn_aceptar.setText("ACEPTAR");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_volver.setBackground(new java.awt.Color(102, 102, 102));
        btn_volver.setForeground(new java.awt.Color(255, 255, 255));
        btn_volver.setText("VOLVER");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        pane_fondo_N1.setBackground(new java.awt.Color(176, 176, 176));

        lbl_Contrasenia.setBackground(new java.awt.Color(238, 238, 238));
        lbl_Contrasenia.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Contrasenia.setText("CONTRASEÑA");

        javax.swing.GroupLayout pane_fondo_N1Layout = new javax.swing.GroupLayout(pane_fondo_N1);
        pane_fondo_N1.setLayout(pane_fondo_N1Layout);
        pane_fondo_N1Layout.setHorizontalGroup(
            pane_fondo_N1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_N1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(lbl_Contrasenia)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        pane_fondo_N1Layout.setVerticalGroup(
            pane_fondo_N1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fondo_N1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Contrasenia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtcontrasenia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcontrasenia.setText("Contraseña");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pane_fondo_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDireccion))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pane_fondo_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(txtApellidop))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pane_fondo_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pane_fondo_N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(txtNrTelefono)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pane_fondo_identifi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(pane_fondo_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdentificacion)
                                    .addComponent(txtNombre)))
                            .addComponent(pane_fondo_Nuevo_Cliente1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(pane_fondo_Nombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(txtApellidom)))
                        .addGap(3, 3, 3)))
                .addGap(114, 114, 114))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(pane_fondo_N1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtcontrasenia)
                .addGap(111, 111, 111))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pane_fondo_Nuevo_Cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pane_fondo_identifi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdentificacion))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pane_fondo_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombre))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pane_fondo_Nombre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtApellidop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pane_fondo_Nombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pane_fondo_direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDireccion))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pane_fondo_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pane_fondo_N, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNrTelefono))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pane_fondo_N1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtcontrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        //Recolectar los Datos
        Empleado empleado = new Empleado();
        empleado.setRutEmpleado(this.txtIdentificacion.getText());
        
        if(empleado.validarRut(txtIdentificacion.getText())){
            empleado.setRutEmpleado(this.txtIdentificacion.getText());
        }else{
         JOptionPane.showMessageDialog(this, "El RUT ingresado es INVALIDO","Validación", JOptionPane.WARNING_MESSAGE);
        }
        
        empleado.setNombre(this.txtNombre.getText());
        empleado.setApellidoP(this.txtApellidop.getText());
        empleado.setApellidoM(this.txtApellidom.getText());;
        empleado.setDireccion(this.txtDireccion.getText());
        
        
        if(empleado.validarEmail(txtEmail.getText())){
            empleado.setEmail(this.txtEmail.getText());
        }else{
         JOptionPane.showMessageDialog(this, "El EMAIL ingresado es INVALIDO","Validación", JOptionPane.WARNING_MESSAGE);
        }
        
        
        empleado.setTelefono(this.txtNrTelefono.getText());
        empleado.setContrasenia(this.txtcontrasenia.getText());
        
        
        

        //Guardo los datos en la BD
        Empleado con = new Empleado();
        
        if(con.guardarVendedor(empleado)){
            
        JOptionPane.showMessageDialog(this, "SE GUARDO CORRECTAMENTE","Validación", JOptionPane.WARNING_MESSAGE);
        }else{
            
          JOptionPane.showMessageDialog(this, "HUBO UN ERROR AL GUARDAR LOS DATOS","Validación", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void txtApellidomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidomActionPerformed

    private void txtIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevo_Vendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Contrasenia;
    private javax.swing.JLabel lbl_Direccion;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_Nombre1;
    private javax.swing.JLabel lbl_Nombre3;
    private javax.swing.JLabel lbl_e_email;
    private javax.swing.JLabel lbl_identificacion;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JPanel pane_fondo_N;
    private javax.swing.JPanel pane_fondo_N1;
    private javax.swing.JPanel pane_fondo_Nombre;
    private javax.swing.JPanel pane_fondo_Nombre1;
    private javax.swing.JPanel pane_fondo_Nombre3;
    private javax.swing.JPanel pane_fondo_Nuevo_Cliente1;
    private javax.swing.JPanel pane_fondo_direccion;
    private javax.swing.JPanel pane_fondo_email;
    private javax.swing.JPanel pane_fondo_identifi;
    private javax.swing.JTextField txtApellidom;
    private javax.swing.JTextField txtApellidop;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNrTelefono;
    private javax.swing.JTextField txtcontrasenia;
    // End of variables declaration//GEN-END:variables
}
